# Generated by Django 3.1.5 on 2021-01-15 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0002_auto_20210115_0321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KnowsFrom',
        ),
        migrations.DeleteModel(
            name='TicketDate',
        ),
        migrations.DeleteModel(
            name='TypeOfCounterparties',
        ),
        migrations.AddField(
            model_name='counterparties',
            name='channel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='counterparties.channel', verbose_name='Ширина канала'),
        ),
        migrations.AddField(
            model_name='counterparties',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='counterparties.cities', verbose_name='Нас. пункт'),
        ),
        migrations.AddField(
            model_name='counterparties',
            name='knowsFrom',
            field=models.CharField(choices=[(1, 'От менеджера отдела продаж'), (2, 'Наружная реклама')], default=None, max_length=256, verbose_name='Откуда узнали об услугах'),
        ),
        migrations.AddField(
            model_name='counterparties',
            name='ticketDate',
            field=models.DateField(default=None, verbose_name='Дата заявки'),
        ),
        migrations.AddField(
            model_name='counterparties',
            name='typeOfService',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='counterparties.typeofservice', verbose_name='Тип услуги'),
        ),
        migrations.AlterField(
            model_name='counterparties',
            name='manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='counterparties.manager', verbose_name='Менеджер'),
        ),
    ]
