# Generated by Django 3.1.5 on 2021-01-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0003_auto_20210115_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparties',
            name='type_of_counterparties',
            field=models.CharField(choices=[(1, 'Физическое Лицо'), (2, 'Юридическое лицо')], default=None, max_length=256, verbose_name='Тип контрагента'),
        ),
    ]
