# Generated by Django 3.1.5 on 2021-01-15 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0004_auto_20210115_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowsFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knows_from', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfCP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_cp', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='counterparties',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='counterparties.cities', verbose_name='Нас. пункт'),
        ),
        migrations.AlterField(
            model_name='counterparties',
            name='knowsFrom',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='counterparties.knowsfrom', verbose_name='Откуда узнали об услугах'),
        ),
        migrations.AlterField(
            model_name='counterparties',
            name='type_of_counterparties',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='counterparties.typeofcp', verbose_name='Тип контрагента'),
        ),
    ]
